version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: ./backend
    command: sh -c "python manage.py collectstatic &&
                    gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/backend
      - static:/usr/src/backend/static
      - media:/usr/src/backend/media
    ports:
      - 8000:8000
    networks:
      - main
  
  nginx:
    container_name: ${PROJECT_NAME}-nginx 
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/usr/src/backend/static
      - media:/usr/src/backend/media
    ports:
      - 80:80
    networks:
      - main


networks:
  main:
    driver: bridge

volumes:
  # postgres_data: {}
  static: {}
  media: {}