version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: ./backend
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME} \
                    DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL} \
                    DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD} \
                    python manage.py createsuperuser --noinput &&
                    python manage.py collectstatic &&
                    gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/backend
      - ./backend/static:/usr/src/backend/static
      - ./backend/media:/usr/src/backend/media
    ports:
      - 8000:8000
    networks:
      - main
  
  nginx:
    container_name: ${PROJECT_NAME}-nginx 
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/usr/src/backend/static
      - media:/usr/src/backend/media
    ports:
      - 80:80
    networks:
      - main
  
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_data: {}
  static: {}
  media: {}