version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/backend/
      - static:/usr/src/app/backend/staticfiles
      - media:/usr/src/app/backend/mediafiles
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: >
      /bin/sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME} \
      DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD} \
      python manage.py createsuperuser --noinput &&
      gunicorn --bind 0.0.0.0:8000 backend.wsgi
      "
    networks:
      - main
      
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build: ./nginx
    image: nginx:1.21-alpine
    volumes:
    # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - static:/usr/src/app/backend/staticfiles
    - media:/usr/src/app/backend/mediafiles
    ports:
      - 80:80
    depends_on:
      - backend

networks:
  main:
    driver: bridge

volumes:
  postgres_data: {}
  static: {}
  media: {}