version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/backend   
      - static:/usr/src/backend/static
      - media:/usr/src/backend/media
    ports:
      - 8000:8000
    networks:
      - main
  
  nginx:
    container_name: ${PROJECT_NAME}-nginx 
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/usr/src/backend/static
      - media:/usr/src/backend/media
    ports:
      - 80:80
    networks:
      - main
  
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main

  frontend:
    container_name: ${PROJECT_NAME}-frontend
    build: ./frontend
    depends_on:
      - backend
      - postgres
    volumes:
      - ./frontend/:/usr/src/frontend
      # - ./frontend/node_modules:/usr/src/frontend/node_modules
      - /usr/src/frontend/node_modules
    ports:
      - 5173:5173
    networks:
      - main
      
networks:
  main:
    driver: bridge

volumes:
  postgres_data: {}
  static: {}
  media: {}