version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: 
      context: ./backend
    command: sh -c "poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 8000:8000
    networks:
      - main

networks:
  main:
    driver: bridge

# volumes:
#   postgres_data: {}
#   static_files: {}
#   media_files: {}