version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: ./backend
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/opt/src/app/backend/
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - main
      
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRESQL_DATABASE: ${DB_DATABASE}
      POSTGRESQL_USER: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - main

  # nginx:
  #   container_name: ${PROJECT_NAME}-nginx
  #   volumes:
  #   - ./config/nginx/conf.d:/etc/nginx/conf.d
  #   - static:/opt/services/djangoapp/static
  #   - media:/opt/services/djangoapp/media
  #   ports:
  #     - 1337:80


networks:
  main:
    driver: bridge

volumes:
  postgres_data: {}
  # static: {}
  # media: {}